const test = require('node:test');
const assert = require('node:assert/strict');
const { loadCatalog } = require('../src/catalog');
const { createRecommender } = require('../src/recommend');
const catalog = loadCatalog(); const engine = createRecommender(catalog);
const request = (patch={}) => ({ city:'Алматы',date:'2026-10-07',eventFormat:'свадьба',category:'Ведущий',budgetKzt:2000000,...patch });
const run = async (patch={}) => (await engine.recommend(request(patch))).body;
test('catalog contains all 66 source profiles',()=>assert.equal(catalog.length,66));
test('dense scenario returns 3 and repeat request is deterministic',async()=>{const a=await run(),b=await run();assert.equal(a.shownCount,3);assert.deepEqual(a.cards.map(x=>x.id),b.cards.map(x=>x.id));});
test('busy date changes eligible results',async()=>assert.notDeepEqual((await run()).cards.map(x=>x.id),(await run({date:'2026-10-03'})).cards.map(x=>x.id)));
test('rare category returns matching profiles',async()=>{const b=await run({category:'Инструменталист',budgetKzt:600000});assert.equal(b.outcome,'matched');assert.equal(b.matchedCount,3);});
test('category unavailable is distinct',async()=>assert.equal((await engine.recommend(request({city:'Зарубежье',category:'Флорист'}))).body.outcome,'category_unavailable'));
test('no candidates under 500000 budget',async()=>assert.equal((await run({budgetKzt:500000})).outcome,'no_eligible_candidates'));
test('fewer than three eligible profiles are fully returned',async()=>{const b=await run({date:'2026-10-03'});assert.ok(b.shownCount<3);assert.equal(b.shownCount,b.matchedCount);});
test('language filter is applied as hard constraint',async()=>{const b=await run({language:'казахский'});assert.ok(b.cards.every(c=>c.languages.includes('казахский')));});
test('durationHours filter is applied',async()=>{const b=await run({durationHours:9});assert.ok(b.cards.every(c=>c.maxHours===null||c.maxHours>=9));});
test('unknown max_hours stays eligible for duration',async()=>{const prof=catalog.find(p=>p.city==='Алматы'&&p.categories.includes('Ведущий')&&p.maxHours===null&&!p.busyDates.has('2026-10-07'));assert.ok(prof);const b=await run({durationHours:20});assert.ok(!b.cards.length||b.cards.every(c=>c.maxHours===null||c.maxHours>=20));});
test('busy contractors never appear',async()=>{const b=await run();assert.ok(b.cards.every(c=>!catalog.find(p=>p.id===c.id).busyDates.has('2026-10-07')));});
test('budget filter is enforced',async()=>{const b=await run({budgetKzt:600000});assert.ok(b.cards.every(c=>c.priceFromKzt<=600000));});
test('event format is enforced',async()=>{const b=await run({eventFormat:'конференция'});assert.ok(b.cards.every(c=>catalog.find(p=>p.id===c.id).eventFormats.includes('конференция')));});
test('synthetic profile marker is preserved in rare category',async()=>{const b=await run({category:'Инструменталист',budgetKzt:600000});assert.ok(b.cards.some(c=>c.synthetic));});
test('price imputation marker is preserved',async()=>{const b=await run({category:'Флорист',budgetKzt:2000000});assert.ok(b.cards.some(c=>c.priceImputed));});
test('city imputation marker is preserved when present',async()=>{const p=catalog.find(x=>x.city==='Алматы'&&x.cityImputed);if(!p)return assert.ok(true);const b=await run({category:p.categories[0],budgetKzt:5000000});assert.ok(b.cards.some(c=>c.cityImputed));});
test('preference fallback keeps price order and returns source evidence',async()=>{const b=await run({preferences:'спокойная атмосфера интеллигентный юмор'});assert.equal(b.ai,'fallback');assert.deepEqual(b.cards.map(c=>c.priceFromKzt),[...b.cards].map(c=>c.priceFromKzt).sort((a,b)=>a-b));assert.ok(b.cards[0].evidence.length);});
test('empty optional fields are accepted',async()=>assert.equal((await run({language:'',durationHours:'',preferences:''})).outcome,'matched'));
test('invalid request gives 400',async()=>{const r=await engine.recommend({city:'Алматы'});assert.equal(r.status,400);});
test('hard filters apply before preference ranking',async()=>{const b=await run({preferences:'свадьба музыка уютно',budgetKzt:600000});assert.ok(b.cards.every(c=>c.priceFromKzt<=600000));});
test('calendar limits come from explicit configuration',async()=>assert.deepEqual(engine.meta().calendarRange,{min:'2026-09-23',max:'2026-12-31'}));
